language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

env:
  - WP_VERSION=4.0 WP_MULTISITE=0 # Minimum required version
  - WP_VERSION=4.4 WP_MULTISITE=0 # Introduction of Responsive Images
  - WP_VERSION=4.7 WP_MULTISITE=0 # Introduction of REST API
  - WP_VERSION=4.8 WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=0

# disable some builds since travis fails when a phpunit test is set to runInSeparateProcess and this test raises deprecation warnings
matrix:
  exclude:
  - php: 7.0
    env: WP_VERSION=4.0 WP_MULTISITE=0
  - php: 7.1
    env: WP_VERSION=4.0 WP_MULTISITE=0
  - php: 7.2
    env: WP_VERSION=4.0 WP_MULTISITE=0

before_script:
  - bash scripts/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer install
  - bin/phpcs --config-set installed_paths vendor/wp-coding-standards/wpcs

script:
  - scripts/phpcodesniffer.sh
  - scripts/unit-tests.sh
