name: Lint Test Deploy

on: [push]

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm ci
          composer install

      - name: Run linter
        run: |
          npm run lint
          composer lint

  tests:
    name: Tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: [
            '5.6'
            #'7.0',
            #'7.1',
            #'7.2',
            #'7.3'
        ]
        wp-versions: [
            #'4.0', # Minimum required version
            '4.4' # Introduction of Responsive Images
            #'4.7', # Introduction of REST API
            #'4.9.18', # Last 4.x version
            #'5.0', # Introduction of Gutenberg
            #'5.3', # Changes in generating srcset
            #'5.8.1' # Latest
        ]
        exclude: # exclude PHP >= 7 and WP 4.0 combinations because of PHP Fatal error: 'break' not in the 'loop' or 'switch' context
          - php-versions: 7.0
            wp-versions: 4.0
          - php-versions: 7.1
            wp-versions: 4.0
          - php-versions: 7.2
            wp-versions: 4.0
          - php-versions: 7.3
            wp-versions: 4.0
          - php-versions: 7.4
            wp-versions: 4.0
          - php-versions: 7.3
            wp-versions: 4.4
          - php-versions: 7.3
            wp-versions: 4.7
          - php-versions: 7.3
            wp-versions: 4.9.18

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm ci
          composer install

      - name: "Configure environment with WP ${{ matrix.wp-versions }} / PHP ${{ matrix.php-versions }}"
        run: |
          echo -e '{\n\t"core": "WordPress/WordPress#${{ matrix.wp-versions }}",\n\t"phpVersion": "${{ matrix.php-versions }}"\n}' > ./.wp-env.override.json

      - name: Install WordPress
        run: |
          chmod -R 767 ./ # TODO: Possibly integrate in wp-env
          npm run wp-env start --debug

      - name: Running PHP unit tests
        run: npm run test:unit:php:ci

  deploy-dry-run:
    name: '[DRY RUN] Deploy'

    # only run on master but not tags
    if: ${{ github.ref == 'refs/heads/master' && !startsWith(github.ref, 'refs/tags/') }}

    needs: [ lint, tests ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3

      - shell: bash
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          DRYRUN=true scripts/deploy-wp-plugin.sh

  deploy:
    name: Deploy

    # only run on tags
    if: startsWith(github.ref, 'refs/tags/')

    needs: [ lint, tests ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - shell: bash
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          scripts/deploy-wp-plugin.sh
